### PR TITLE
Fixed Globus API call for fetching user information in Java auth library

### PR DESCRIPTION
**Pull request by msneddon**
Identical to https://github.com/kbase/auth/pull/14, but this time against the develop branch.  See https://github.com/kbase/auth/pull/14 for more details and discussion on this PR.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
This seems ok to me.  @scanon , @briehl , @eapearson can you review as well?

**Comment by kkellerlbl** [comment]
There are related PRs for jars and workspace_deluxe I believe.

**Comment by scanon** [comment]
I'm okay with it

**Comment by briehl** [comment]
Looks good to me :+1:

**Comment by kkellerlbl** [comment]
Merging based on KBASE-2024.

**Comment by MrCreosote** [comment]
I should point out here that you're swapping one problem for another. If you use the original (i.e. pre-PR) url, the client can only see users in the kbase_users group, but can see them whether their profile is set to private or not. With the new url, you can only see public users, but obviously you can see them outside of kbase_users.

The change in the previous PR was meant to fix the private users problem (at the time my understanding from Steve was that the auth service wouldn't hand out tokens unless the user was in the kbase_users group; that's obviously not the case). This PR will result in all private users being invisible again.

Another minor point - there's no need to make changes to the java auth client on the develop branch since the code isn't imported directly, but via a jar import from the jars repo.

**Comment by MrCreosote** [comment]
BTW, the PR that changed the URL the first time is https://github.com/kbase/auth/pull/9.

**Comment by eapearson** [comment]
> On Jun 2, 2015, at 7:25 PM, MrCreosote <notifications@github.com> wrote:
> 
> I should point out here that you're swapping one problem for another. If you use the original (i.e. pre-PR) url, the client can only see users in the kbase_users group, but can see them whether their profile is set to private or not. With the new url, you can only see public users, but obviously you can see them outside of kbase_users.
> 
The new url (/users call) combined with the workspace test account used to generate the access token provides a view of user accounts that seems to adhere to the Globus policy. Accounts in the KBase users group set to globus-wide or group-only and accounts not in kbase_users but with globus-wide privacy will be validated. 

The good news is that there are very few users in these categories, 6 (4 user/2 kbase) in kbase_users and 2 (1 user, 1 kbase) not in kbase_users. 

The /groups/members call loses more accounts — 256 (192 user, 64 kbase). 2 of those included in the set above (the users not in kbase_users). The groups/members call does indeed include the 6 kbase_users accounts which have specified the stricter privacy setting, but this is surely a bug. The Globus user interface does honor the privacy of those accounts and they are not visible to a regular kbase user. 

Rather than provide the special wstest globus account used to verify usernames with group manager access, we will be reaching out to these users to let them know that their accounts are misconfigured and that certain features of kbase will be unavailable until they are fixed (something like that.)

It is also notable that the /users call does return a json object indicating the nature of the error if the user exists but has privacy blocking their profile, which does provide evidence that the user exists; the response for a non-existent user is empty. We could use this error response as validation of the user, although it is a bit fragile to rely on error message text.

This should all become moot sometime when we have an actual user database, registration, etc. on the kbase side and do not need to make calls over to Globus like this.

Erik.

**Pull request merged**
