### PR TITLE
Changes required for http support (used by fake auth service).

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by eapearson** [comment]
What is the fake auth service? Why would you not want to even fake over https? Shouldn't https  be a requirement when carrying sensitive auth info like a token? And faking is the perfect time to ensure that the requirement is never violated because you can set up both ends exactly as you wish. Enlighten me!

**Comment by rsutormin** [comment]
Well, the idea was to start up for tests local fake auth service mocking real one (and it will be shut down after tests are done). Since it's started locally it will be based on http rather than https. When you use fake auth service you never send any real passwords (password should match user login actually in our fake case). So why do you worry about real token?

**Comment by eapearson** [comment]
Okay, here is my thinking. A requirement for all auth code is that it operate over https. So any test that operates over http is invalid, by definition. My worry is not that the act of running that test creates some sort of important security or privacy breach. Now if the point of using http is to trigger an exception or other test failure, that is a different matter :)

**Comment by rsutormin** [comment]
Please don't forget about devel mode when you have to deploy fake service locally and trace errors from clients calling it outside. In this case http support is necessary. I agree with your point that it should be public service in production. And there is no problem with requirement to never deploy it as http for production.

**Comment by msneddon** [comment]
A sidenote- it seems like there might be some complementary effort here with: https://github.com/kbase/nexus_emulation ?

This also brings up the question of whether we should have kbase code connecting directly to globus, or if instead we always use our own auth service that for now just forwards requests to globus.  Right now I believe we do both things in different places...

My personal opinion is in favor of our own auth service so that we can add features as needed, centralize some user logging, and deal with problems from unexpected changes in the globus api in one place, which actually just happened recently: https://atlassian.kbase.us/browse/WOR-209

Either way, we do need to emulate authentication in kbase soon in order to setup Travis CI for authenticated services in a way that pull requests can all be tested.

**Comment by mlhenderson** [comment]
Having a KBase auth api that simply talks to globus internally is much more
flexible.

**Pull request closed without merging**
